### ISSUE TITLE
Add navigation links

### ISSUE THREAD

**Issue by h-m-m** [rubyforgood/working_landscapes#67]
Breadcrumb links or similar workflow indication should be on every page to help with how to navigate the site.

The current workflow is something like:

Manage Sites | Manage Protocols | > Add Observations >  Add Samples > Add Entries

**Comment by h-m-m** [comment]
Manage Sites should link to `/admin/sites`
Manage Protocols should link to `/survey_protocols`
Add Observations should link to `/observations/new`
Links to add Samples should only show up once you're starting a new / editing an existing observation, because they are relative to the observation. They will link to `/observations/:observation_id/samples/new`

**Comment by pollygee** [comment]
I'm going to give this issue a go.  I can't assign it to myself so I don't know if I need to be added to the project or if that matters.  I just didn't want anyone else to be simultaneously working on this issue.

**Comment by kalimar** [comment]
I'm going to add @pollygee to Ruby for good. I think that's the issue. We'll find out :)

**Comment by kalimar** [comment]
Nope that wasn't the issue. I bet @seanmarcia knows though

**Comment by kalimar** [comment]
Figured it out. Woot

**Comment by pollygee** [comment]
@h-m-m I have added some stuff, I haven't used Active Admin before so it's been a little slow going.  But I added a link to the landing page to get to the Admin Dashboard.  And I added a link to Manage Sites on the Admin Dashboard.  My changes are on a branch https://github.com/rubyforgood/working_landscapes/tree/add_links.

I am a little confused from here and want to check in before I go further.  From what I'm reading it looks like you want to link from Manage Sites back to Manage Protocols, is that Correct?  So link back out of Admin?  Do you just want that at the bottom of the columns there?

Also I wanted to ask about the breadcrumbs because I was going to add the breadcrumbs to navigate back to previous pages.  But the breadcrumbs are in the Active Admin pages but not in the regular app pages, so are you wanting me to add breadcrumbs to those pages as well?  

Thanks for the clarification.

**Comment by h-m-m** [comment]
@pollygee Your changes look great. 
Do you think we should remove the "About" and "Contact" links in the nav bar?

I'm not sure I have an answer to your question about whether there should be a link on the manage sites page to go back out an manage protocols. The best suggestion I can think of right now is to put something in there, put it in front of users, and ask them if they like it. I'll get to work on setting that up.

As for your question about breadcrumbs, I'm not looking for a complete breadcrumb system like what Active Admin uses. What that may have been my original thought last summer, after we talked in December, I think starting with something simple and then iterating on it is the better choice here.

To that end, a link that shows up when you're editing an observation that takes you to adding a new sample for that observation is enough for now. The location of the link can be wherever you feel works best.

**Comment by pollygee** [comment]
@h-m-m sounds good, I wondered about the "about" and "contact" but didn't know if there were plans to use that in the future.  I'll get rid of them and take my best guess at the rest and then we can get feedback and go from there.

**Comment by pollygee** [comment]
@h-m-m I've made some more changes, added some more links and pushed it to my branch.

It sounds like you wanted me to add a link to the editing observation page.  But maybe it should be on the show page, because on the edit page you would want to save the changes before adding a sample.

That said, right now I can't get the "Update Observation" button to work it fails in observations_controller.rb.  in the show method.  I was thinking that `show_observation_path` maybe needs to be `observation_path` because I don't see one with show in it, but then it fails in the show method.  Can you take a look at that and let me know if you see anything?  Thanks!

**Comment by h-m-m** [comment]
This is good, and I had no problem deploying it to Heroku. I'm going to open up a new issue for any further link / workflow issues we find that can be similarly resolved.

**Comment by pollygee** [comment]
Yay!  That's awesome!!
